### ISSUE TITLE
Problema nella concatenazione di matrici in Processing.m

### ISSUE THREAD

**Issue by LauraToni** [LauraToni/Progetto_cmepda#1]
Qualcosa non funziona nella sezione ''Read NifTi files" di Processing.m, le matrici non vengono concatenate correttamente e non è possibile usarle nelle funzioni successive.

**Comment by IreneTenerani** [comment]
Era sufficiente definire Image_AD e Image_CTRL come matrici, parentesi quadre, e non come un cell array, parentesi graffe.
