### ISSUE TITLE
Problema nell'ordinamento dei file in CNN.py

### ISSUE THREAD

**Issue by IreneTenerani** [LauraToni/Progetto_cmepda#2]
I file contenenti le immagini NifTi di casi e controlli vengono caricate in modo non ordinato in CNN.py, questo rende difficile avere una corrispondenza tra il file AD_CTRL_metadata_labels.csv, contenente i metadati, e le immagini a cui i metadati fanno riferimento.

**Comment by LauraToni** [comment]
Risolto questo problema nel file input_dati.py usando la funzione sorted() di glob che ordina i dati come nel csv
